### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by karthikkaushal** [subramanya1997/cryptocurrency-price-prediction#1]
Good work buddy..it seems to be an exhaustive research. My personal view is that historical open High low close and volume  do not contribute to prediction of asset prices. Historical stock price levels are non stationary which means that they don't have an underlying pattern.The second plot which shows an attractive overlapping of prediction and actual prices is because of bias of previous  price which eventually means that next days prediction would be somewhere around previous days price.Inorder to achieve what you are trying to do you should train the model till a certain day and from that day predict prices for next 20 or 30 days without training the model with data related to those 20 or 30 days and then you could see if plots overlap.
Anyways you've ventured into something exciting..good luck!

**Comment by subramanya1997** [comment]
Thanks buddy.. The data is split into training and testing data (80:20). What you see in the second picture is a model predicting on the test data which has been trained using training data set.
